
create extension if not exists "uuid-ossp";
create type user_role as enum ('admin','coach','viewer');
create type player_status as enum ('active','injured','inactive','trial','guest');
create type player_position as enum ('goalkeeper','defender','midfielder','winger','forward');
create type session_type as enum ('training','league_match','friendly_match','tryout','scrimmage');
create type session_status as enum ('planned','completed','cancelled','locked');
create type callup_status as enum ('called_up','trial','guest_not_evaluable','injured','doubt','not_called');
create type attendance_status as enum ('present','late','justified_late','justified_absence','unjustified_absence','injured');
create type card_type as enum ('yellow','double_yellow','straight_red');
create type injury_status as enum ('active','recovered','pending_review','minor_discomfort');

create table profiles (id uuid primary key references auth.users(id) on delete cascade,email text not null,full_name text,role user_role not null default 'viewer',created_at timestamptz not null default now());
create table players (id uuid primary key default uuid_generate_v4(),name text not null,nickname text,display_name text generated always as (coalesce(nullif(nickname,''),name)) stored,position player_position,shirt_number int,status player_status not null default 'active',notes text,created_at timestamptz not null default now());
create table sessions (id uuid primary key default uuid_generate_v4(),name text not null,session_date date not null,start_time time,type session_type not null,responsible text,status session_status not null default 'planned',opponent text,home_away text check (home_away in ('home','away','neutral') or home_away is null),result text,high_rating_limit int not null default 6,locked_at timestamptz,notes text,created_at timestamptz not null default now());
create table callups (id uuid primary key default uuid_generate_v4(),session_id uuid not null references sessions(id) on delete cascade,player_id uuid not null references players(id) on delete cascade,status callup_status not null default 'called_up',evaluable boolean not null default true,notes text,created_at timestamptz not null default now(),unique(session_id,player_id));
create table attendance (id uuid primary key default uuid_generate_v4(),session_id uuid not null references sessions(id) on delete cascade,player_id uuid not null references players(id) on delete cascade,status attendance_status not null default 'present',notes text,submitted_by uuid references profiles(id),submitted_at timestamptz not null default now(),unique(session_id,player_id));
create table evaluations (id uuid primary key default uuid_generate_v4(),session_id uuid not null references sessions(id) on delete cascade,player_id uuid not null references players(id) on delete cascade,tactical_discipline int not null default 3 check (tactical_discipline between 1 and 5),effort_commitment int not null default 3 check (effort_commitment between 1 and 5),decision_making int not null default 3 check (decision_making between 1 and 5),mentality_attitude int not null default 3 check (mentality_attitude between 1 and 5),coachability int not null default 3 check (coachability between 1 and 5),comment text,evaluated boolean not null default false,submitted_by uuid references profiles(id),submitted_at timestamptz not null default now(),total_score numeric generated always as (round(((tactical_discipline+effort_commitment+decision_making+mentality_attitude+coachability)::numeric/5),2)) stored,unique(session_id,player_id));
create table cards (id uuid primary key default uuid_generate_v4(),session_id uuid not null references sessions(id) on delete cascade,player_id uuid not null references players(id) on delete cascade,type card_type not null,minute text,reason text,notes text,created_at timestamptz not null default now());
create table injuries (id uuid primary key default uuid_generate_v4(),player_id uuid not null references players(id) on delete cascade,session_id uuid references sessions(id) on delete set null,start_date date not null default current_date,end_date date,status injury_status not null default 'active',body_area text,injury_type text,severity text,notes text,created_at timestamptz not null default now());

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,email,full_name,role) values(new.id,new.email,coalesce(new.raw_user_meta_data->>'full_name',''),'viewer'); return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users; create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create or replace function public.current_role() returns user_role language sql stable as $$ select role from profiles where id=auth.uid() $$;
create or replace function public.prevent_locked_session_edits() returns trigger language plpgsql as $$ declare locked boolean; begin select (status='locked' or locked_at is not null) into locked from sessions where id=coalesce(new.session_id,old.session_id); if locked and public.current_role()<>'admin' then raise exception 'This session is locked and can only be edited by an admin.'; end if; return new; end; $$;
create or replace function public.enforce_high_rating_limit() returns trigger language plpgsql as $$ declare lim int; cnt int; begin select high_rating_limit into lim from sessions where id=new.session_id; if new.tactical_discipline>=4 then select count(*) into cnt from evaluations where session_id=new.session_id and tactical_discipline>=4 and id<>coalesce(new.id,'00000000-0000-0000-0000-000000000000'::uuid); if cnt>=lim then raise exception 'Maximum high ratings reached for Tactical Discipline.'; end if; end if; if new.effort_commitment>=4 then select count(*) into cnt from evaluations where session_id=new.session_id and effort_commitment>=4 and id<>coalesce(new.id,'00000000-0000-0000-0000-000000000000'::uuid); if cnt>=lim then raise exception 'Maximum high ratings reached for Effort / Commitment.'; end if; end if; if new.decision_making>=4 then select count(*) into cnt from evaluations where session_id=new.session_id and decision_making>=4 and id<>coalesce(new.id,'00000000-0000-0000-0000-000000000000'::uuid); if cnt>=lim then raise exception 'Maximum high ratings reached for Decision Making.'; end if; end if; if new.mentality_attitude>=4 then select count(*) into cnt from evaluations where session_id=new.session_id and mentality_attitude>=4 and id<>coalesce(new.id,'00000000-0000-0000-0000-000000000000'::uuid); if cnt>=lim then raise exception 'Maximum high ratings reached for Mentality / Attitude.'; end if; end if; if new.coachability>=4 then select count(*) into cnt from evaluations where session_id=new.session_id and coachability>=4 and id<>coalesce(new.id,'00000000-0000-0000-0000-000000000000'::uuid); if cnt>=lim then raise exception 'Maximum high ratings reached for Coachability.'; end if; end if; return new; end; $$;
create trigger trg_evaluations_high_limit before insert or update on evaluations for each row execute procedure public.enforce_high_rating_limit();
create trigger trg_attendance_locked before insert or update or delete on attendance for each row execute procedure public.prevent_locked_session_edits();
create trigger trg_evaluations_locked before insert or update or delete on evaluations for each row execute procedure public.prevent_locked_session_edits();
create trigger trg_cards_locked before insert or update or delete on cards for each row execute procedure public.prevent_locked_session_edits();

create or replace view session_evaluation_summary as select s.id session_id,s.name session_name,s.session_date,count(e.id) total_evaluations,round(avg(e.total_score),2) average_score,count(*) filter(where e.tactical_discipline>=4) high_tactical,count(*) filter(where e.effort_commitment>=4) high_effort,count(*) filter(where e.decision_making>=4) high_decision,count(*) filter(where e.mentality_attitude>=4) high_mentality,count(*) filter(where e.coachability>=4) high_coachability from sessions s left join evaluations e on e.session_id=s.id group by s.id;
create or replace view player_overview as select p.id,p.display_name,p.name,p.nickname,p.position,p.shirt_number,p.status,coalesce(count(c.id) filter(where c.type='yellow'),0)+coalesce(count(c.id) filter(where c.type='double_yellow'),0)*2 yellow_cards,coalesce(count(c.id) filter(where c.type in ('straight_red','double_yellow')),0) red_cards,round(avg(e.total_score),2) average_score,count(i.id) filter(where i.status='active') active_injuries from players p left join cards c on c.player_id=p.id left join evaluations e on e.player_id=p.id left join injuries i on i.player_id=p.id group by p.id;

alter table profiles enable row level security; alter table players enable row level security; alter table sessions enable row level security; alter table callups enable row level security; alter table attendance enable row level security; alter table evaluations enable row level security; alter table cards enable row level security; alter table injuries enable row level security;
create policy "profiles read own or admin" on profiles for select using(id=auth.uid() or public.current_role()='admin'); create policy "profiles admin update" on profiles for update using(public.current_role()='admin');
create policy "read players" on players for select using(auth.uid() is not null); create policy "admin manage players" on players for all using(public.current_role()='admin') with check(public.current_role()='admin');
create policy "read sessions" on sessions for select using(auth.uid() is not null); create policy "admin manage sessions" on sessions for all using(public.current_role()='admin') with check(public.current_role()='admin');
create policy "read callups" on callups for select using(auth.uid() is not null); create policy "admin manage callups" on callups for all using(public.current_role()='admin') with check(public.current_role()='admin');
create policy "read attendance" on attendance for select using(auth.uid() is not null); create policy "coach admin manage attendance" on attendance for all using(public.current_role() in ('admin','coach')) with check(public.current_role() in ('admin','coach'));
create policy "read evaluations" on evaluations for select using(auth.uid() is not null); create policy "coach admin manage evaluations" on evaluations for all using(public.current_role() in ('admin','coach')) with check(public.current_role() in ('admin','coach'));
create policy "read cards" on cards for select using(auth.uid() is not null); create policy "coach admin manage cards" on cards for all using(public.current_role() in ('admin','coach')) with check(public.current_role() in ('admin','coach'));
create policy "read injuries" on injuries for select using(auth.uid() is not null); create policy "coach admin manage injuries" on injuries for all using(public.current_role() in ('admin','coach')) with check(public.current_role() in ('admin','coach'));
