import { useEffect, useState } from 'react';
import { CheckCircle2, RotateCcw } from 'lucide-react';
import { supabase } from '../supabase';
import type { Attendance, Player, Role } from '../types';
import type { AppSession } from '../utils/appTypes';
import { attendanceNeedsExplanation, attendanceOptions } from '../utils/appTypes';
import { translatePosition } from '../utils/formatters';
import { Card, PageTitle } from '../components/ui';

export function AttendancePage({ role, session, players, attendance, reload, setError, moveToNextOpenSession }: { role: Role; session: AppSession; players: Player[]; attendance: Attendance[]; reload: any; setError: any; moveToNextOpenSession: any; }) {
  const [explanation, setExplanation] = useState<Record<string, string>>({}); const [localLocked, setLocalLocked] = useState(!!session.attendance_confirmed); const locked = localLocked; const isAdmin = role === 'admin';
  useEffect(() => { setLocalLocked(!!session.attendance_confirmed); }, [session.attendance_confirmed]);
  async function confirmAttendance() { if (!window.confirm('¿Confirmar asistencia? El coach no podrá modificarla después.')) return; const { error } = await supabase.from('sessions').update({ attendance_confirmed: true, attendance_confirmed_at: new Date().toISOString() }).eq('id', session.id); if (error) { setError(error.message); return; } setLocalLocked(true); await reload(session.id); if (session.callup_confirmed && session.evaluation_confirmed) await moveToNextOpenSession(); }
  async function reopenAttendance() { if (!isAdmin) return; if (!window.confirm('¿Reabrir asistencia? Esto permitirá hacer cambios otra vez.')) return; const { error } = await supabase.from('sessions').update({ attendance_confirmed: false, attendance_confirmed_at: null }).eq('id', session.id); if (error) { setError(error.message); return; } setLocalLocked(false); await reload(session.id); }
  async function update(playerId: string, status: string) { if (locked) return; setError(''); const existing = attendance.find(a => a.player_id === playerId); const notes = explanation[playerId] || existing?.notes || ''; const payload = { session_id: session.id, player_id: playerId, status, notes: attendanceNeedsExplanation.includes(status) ? notes : null }; const res = existing ? await supabase.from('attendance').update(payload).eq('id', existing.id) : await supabase.from('attendance').insert(payload); if (res.error) setError(res.error.message); else reload(session.id); }
  return <div className="stack"><PageTitle title={`Asistencia: ${session.name}`} subtitle="Marca asistencia para la sesión seleccionada." /><Card className={locked ? 'locked-card confirmed-card' : ''}><p className="kicker">Estado</p><h2>{locked ? 'Asistencia cerrada' : 'Asistencia abierta'}</h2>{locked ? <div className="stack"><button className="primary confirmed" disabled><CheckCircle2 size={18} /> Asistencia cerrada</button>{isAdmin && <button className="secondary danger" onClick={reopenAttendance}><RotateCcw size={16} /> Reabrir asistencia</button>}</div> : <button className="primary" onClick={confirmAttendance}>Confirmar asistencia</button>}</Card>{players.map((p: Player) => { const rec = attendance.find(a => a.player_id === p.id); const current = rec?.status || 'present'; const needs = attendanceNeedsExplanation.includes(current); const missingNote = needs && !(explanation[p.id] || rec?.notes || '').trim(); return <Card key={p.id} className={missingNote ? 'needs-note' : ''}><div className="row"><strong>{p.display_name}</strong><span>{translatePosition(p.position)}</span></div>{needs && <><textarea disabled={locked} placeholder="Explicación recomendada..." value={explanation[p.id] ?? rec?.notes ?? ''} onChange={e => setExplanation({ ...explanation, [p.id]: e.target.value })} />{missingNote && <p className="tiny-warning">Explicación pendiente/recomendada.</p>}</>}<div className="chips">{attendanceOptions.map(([value, label]) => <button disabled={locked} key={value} className={current === value ? 'chip active' : 'chip'} onClick={() => update(p.id, value)}>{label}</button>)}</div></Card>; })}</div>;
}
