import { useEffect, useMemo, useState } from 'react';
import { CheckCircle2, ChevronRight, RotateCcw, Search } from 'lucide-react';
import { supabase } from '../supabase';
import type { Evaluation, Player, Role } from '../types';
import type { AppSession } from '../utils/appTypes';
import { cardOptions, ratingFields } from '../utils/appTypes';
import { cleanDbError, translatePosition } from '../utils/formatters';
import { getRatingCounts } from '../utils/stats';
import { Card, PageTitle } from '../components/ui';

export function EvaluationPage({ role, session, players, evaluations, reload, setError, moveToNextOpenSession }: { role: Role; session: AppSession; players: Player[]; evaluations: Evaluation[]; reload: any; setError: any; moveToNextOpenSession: any; }) {
  const [index, setIndex] = useState(0); const [cardType, setCardType] = useState('none'); const [cardReason, setCardReason] = useState(''); const [localLocked, setLocalLocked] = useState(!!session.evaluation_confirmed);
  const locked = localLocked; const isAdmin = role === 'admin'; const player = players[index]; const ev = evaluations.find(e => e.player_id === player?.id); const counters = useMemo(() => getRatingCounts(evaluations), [evaluations]);
  useEffect(() => { setLocalLocked(!!session.evaluation_confirmed); }, [session.evaluation_confirmed]);
  if (!player) return <p>No hay jugadores para evaluar.</p>;
  async function ensureEval(): Promise<Evaluation | null> { if (ev) return ev; const { data, error } = await supabase.from('evaluations').insert({ session_id: session.id, player_id: player.id }).select('*').single(); if (error) { setError(error.message); return null; } await reload(session.id); return data as Evaluation; }
  async function update(field: string, value: number | string | boolean) { if (locked) return; setError(''); const currentValue = Number((ev as any)?.[field]); const highLimit = session.high_rating_limit || 6; const lowLimit = session.low_rating_limit || 3; if (typeof value === 'number') { const isNewHigh = value >= 4, wasHigh = currentValue >= 4, isNewLow = value <= 2, wasLow = currentValue > 0 && currentValue <= 2; if (isNewHigh && !wasHigh && counters.high[field] >= highLimit) { const msg = 'Has llegado al máximo de jugadores con puntuación alta en esta categoría. Cambia una evaluación anterior para continuar.'; setError(msg); alert(msg); return; } if (isNewLow && !wasLow && counters.low[field] >= lowLimit) { const msg = 'Has llegado al máximo de jugadores con puntuación baja en esta categoría. Cambia una evaluación anterior para continuar.'; setError(msg); alert(msg); return; } } const record = await ensureEval(); if (!record) return; const { error } = await supabase.from('evaluations').update({ [field]: value, submitted_at: new Date().toISOString() }).eq('id', record.id); if (error) setError(cleanDbError(error.message)); else reload(session.id); }
  async function saveCardIfNeeded() { if (locked) return true; if (cardType === 'none') return true; if (!cardReason.trim()) { setError('Si marcas una tarjeta debes añadir el motivo.'); return false; } const { error } = await supabase.from('cards').insert({ session_id: session.id, player_id: player.id, type: cardType, reason: cardReason }); if (error) { setError(error.message); return false; } setCardType('none'); setCardReason(''); return true; }
  async function next() { const ok = await saveCardIfNeeded(); if (!ok) return; await update('evaluated', true); setIndex(i => (i + 1) % players.length); }
  async function confirmEvaluation() { if (!window.confirm('¿Confirmar evaluación? El coach no podrá modificarla después.')) return; const { error } = await supabase.from('sessions').update({ evaluation_confirmed: true, evaluation_confirmed_at: new Date().toISOString() }).eq('id', session.id); if (error) { setError(error.message); return; } setLocalLocked(true); await reload(session.id); if (session.callup_confirmed && session.attendance_confirmed) await moveToNextOpenSession(); }
  async function reopenEvaluation() { if (!isAdmin) return; if (!window.confirm('¿Reabrir evaluación? Esto permitirá hacer cambios otra vez.')) return; const { error } = await supabase.from('sessions').update({ evaluation_confirmed: false, evaluation_confirmed_at: null }).eq('id', session.id); if (error) { setError(error.message); return; } setLocalLocked(false); await reload(session.id); }
  const current: any = ev || { tactical_discipline: 3, effort_commitment: 3, decision_making: 3, mentality_attitude: 3, coachability: 3, comment: '' }; const isMatch = ['friendly_match','league_match','tryout','scrimmage'].includes(session.type); const highLimit = session.high_rating_limit || 6; const lowLimit = session.low_rating_limit || 3;
  return <div className="stack"><PageTitle title={`Evaluación: ${session.name}`} subtitle="Evalúa jugador por jugador." /><Card className={locked ? 'locked-card confirmed-card' : ''}><p className="kicker">Estado evaluación</p><h2>{locked ? 'Evaluación confirmada' : 'Evaluación abierta'}</h2>{locked ? <div className="stack"><button className="primary confirmed" disabled><CheckCircle2 size={18} /> Evaluación confirmada</button>{isAdmin && <button className="secondary danger" onClick={reopenEvaluation}><RotateCcw size={16} /> Reabrir evaluación</button>}</div> : <button className="primary" onClick={confirmEvaluation}>Confirmar evaluación</button>}</Card><div className="progress">{index + 1} / {players.length}</div><Card><div className="search-label"><Search size={16} /> Ir a jugador</div><select value={index} onChange={e => setIndex(Number(e.target.value))}>{players.map((p, i) => <option key={p.id} value={i}>{i + 1}. {p.display_name}</option>)}</select></Card><Card><div className="row"><div><p className="kicker">Jugador</p><h2>{player.display_name}</h2><p>{translatePosition(player.position)}</p></div><div className="score-badge">{current.total_score || '-'}</div></div></Card>{ratingFields.map(([field,label]) => { const highReached = counters.high[field] >= highLimit; const lowReached = counters.low[field] >= lowLimit; return <Card key={field}><div className="row rating-header"><strong>{label}</strong><div className="limit-stack"><span className={highReached ? 'limit danger' : 'limit'}>Altas: {counters.high[field]}/{highLimit}</span><span className={lowReached ? 'limit danger' : 'limit'}>Bajas: {counters.low[field]}/{lowLimit}</span></div></div><div className="rating">{[1,2,3,4,5].map(n => <button disabled={locked} key={n} className={current[field] === n ? 'rate active' : 'rate'} onClick={() => update(field, n)}>{n}</button>)}</div></Card>; })}{isMatch && <Card><strong>Tarjetas</strong><select disabled={locked} value={cardType} onChange={e => setCardType(e.target.value)}>{cardOptions.map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select>{cardType !== 'none' && <textarea disabled={locked} placeholder="Motivo de la tarjeta..." value={cardReason} onChange={e => setCardReason(e.target.value)} />}</Card>}<Card><strong>Comentario corto</strong><textarea disabled={locked} defaultValue={current.comment || ''} onBlur={e => update('comment', e.target.value)} placeholder="Comentario corto..." /></Card><button className="primary" onClick={next} disabled={locked}>Siguiente jugador <ChevronRight size={18} /></button><button className="secondary" disabled={index === 0} onClick={() => setIndex(i => Math.max(0, i - 1))}>Anterior</button></div>;
}
