import { useEffect, useState } from 'react';
import { supabase } from '../supabase';
import type { Player, Role } from '../types';
import type { AppSession } from '../utils/appTypes';
import { translateInjuryStatus } from '../utils/formatters';
import { Card, Modal, PageTitle } from '../components/ui';

export function InjuriesPage({ session, players, reload, setError, role }: { session: AppSession; players: Player[]; reload: any; setError: any; role: Role; }) {
  const [playerId, setPlayerId] = useState(players[0]?.id || ''); const [injuryType, setInjuryType] = useState(''); const [date, setDate] = useState(new Date().toISOString().slice(0,10)); const [notes, setNotes] = useState(''); const [injuries, setInjuries] = useState<any[]>([]); const [selectedInjury, setSelectedInjury] = useState<any | null>(null); const isAdmin = role === 'admin';
  async function loadInjuries() { const { data } = await supabase.from('injuries').select('*, players(display_name)').order('start_date', { ascending: false }); setInjuries(data || []); }
  useEffect(() => { loadInjuries(); }, []);
  async function submit(e: React.FormEvent) { e.preventDefault(); const { error } = await supabase.from('injuries').insert({ session_id: session.id, player_id: playerId, start_date: date, injury_type: injuryType, body_area: injuryType, status: 'active', notes }); if (error) setError(error.message); else { setInjuryType(''); setNotes(''); reload(session.id); loadInjuries(); alert('Lesión registrada'); } }
  async function updateInjury(payload: any) { if (!selectedInjury) return; const { error } = await supabase.from('injuries').update(payload).eq('id', selectedInjury.id); if (error) setError(error.message); else { setSelectedInjury(null); await loadInjuries(); } }
  const active = injuries.filter(i => i.status !== 'recovered'); const recovered = injuries.filter(i => i.status === 'recovered');
  return <div className="stack"><PageTitle title="Lesiones" subtitle="Registra lesiones, revisa fichas y marca altas." /><form className="stack" onSubmit={submit}><Card><h3>Nueva lesión</h3><select value={playerId} onChange={e => setPlayerId(e.target.value)}>{players.map(p => <option key={p.id} value={p.id}>{p.display_name}</option>)}</select><input placeholder="Lesión / zona afectada" value={injuryType} onChange={e => setInjuryType(e.target.value)} required /><input type="date" value={date} onChange={e => setDate(e.target.value)} required /><textarea placeholder="Notas" value={notes} onChange={e => setNotes(e.target.value)} /><button className="primary">Guardar lesión</button></Card></form><Card><p className="kicker">Lesiones abiertas</p>{active.length === 0 && <p>No hay lesiones abiertas.</p>}{active.map(i => <InjuryRow key={i.id} injury={i} onClick={() => setSelectedInjury(i)} />)}</Card><Card><p className="kicker">Lesiones superadas</p>{recovered.length === 0 && <p>No hay lesiones superadas.</p>}{recovered.map(i => <InjuryRow key={i.id} injury={i} onClick={() => setSelectedInjury(i)} />)}</Card>{selectedInjury && <Modal title="Ficha lesión" onClose={() => setSelectedInjury(null)}><div className="stack"><p><strong>{selectedInjury.players?.display_name || 'Jugador'}</strong></p><p>{selectedInjury.start_date} · {selectedInjury.injury_type || selectedInjury.body_area}</p><textarea value={selectedInjury.notes || ''} onChange={e => setSelectedInjury({ ...selectedInjury, notes: e.target.value })} /><button className="primary" onClick={() => updateInjury({ notes: selectedInjury.notes || '' })}>Guardar comentario</button><button className="secondary" onClick={() => updateInjury({ status: 'recovered', end_date: new Date().toISOString().slice(0,10) })}>Dar alta</button>{isAdmin && <button className="secondary danger" onClick={() => updateInjury({ status: 'active', end_date: null })}>Reabrir lesión</button>}</div></Modal>}</div>;
}
function InjuryRow({ injury, onClick }: any) { return <button className="injury-row clickable" onClick={onClick}><div><strong>{injury.players?.display_name || 'Jugador'}</strong><p>{injury.start_date} · {injury.injury_type || injury.body_area} · {translateInjuryStatus(injury.status)}</p></div><span>›</span></button>; }
