import { useEffect, useState } from 'react';
import { Plus } from 'lucide-react';
import { supabase } from '../supabase';
import type { AppSession } from '../utils/appTypes';
import { buildSessionLabel, translateSessionType } from '../utils/formatters';
import { Card, Modal, PageTitle } from '../components/ui';

export function SessionsPage({ reload, selectedSession, setSelectedSession }: any) {
  const [sessions, setSessions] = useState<AppSession[]>([]);
  const [loadingSessions, setLoadingSessions] = useState(true);
  const [message, setMessage] = useState('');
  const [editing, setEditing] = useState<AppSession | null>(null);
  const [showModal, setShowModal] = useState(false);
  const [form, setForm] = useState({ name: '', session_date: new Date().toISOString().slice(0, 10), start_time: '', type: 'training', responsible: '', opponent: '', home_away: 'home', status: 'planned' });
  async function loadSessions() { setLoadingSessions(true); const { data } = await supabase.from('sessions').select('*').order('session_date', { ascending: false }); setSessions((data || []) as AppSession[]); setLoadingSessions(false); }
  useEffect(() => { loadSessions(); }, []);
  function openCreate() { setEditing(null); setForm({ name: '', session_date: new Date().toISOString().slice(0, 10), start_time: '', type: 'training', responsible: '', opponent: '', home_away: 'home', status: 'planned' }); setShowModal(true); }
  function openEdit(session: AppSession) { setEditing(session); setForm({ name: session.name || '', session_date: session.session_date, start_time: session.start_time || '', type: session.type || 'training', responsible: session.responsible || '', opponent: session.opponent || '', home_away: session.home_away || 'home', status: session.status || 'planned' }); setShowModal(true); }
  async function saveSession(e: React.FormEvent) { e.preventDefault(); setMessage(''); const payload = { name: form.name, session_date: form.session_date, start_time: form.start_time || null, type: form.type, responsible: form.responsible || null, opponent: form.opponent || null, home_away: form.home_away || null, status: form.status, high_rating_limit: 6, low_rating_limit: 3 }; const res = editing ? await supabase.from('sessions').update(payload).eq('id', editing.id) : await supabase.from('sessions').insert(payload); if (res.error) { setMessage(res.error.message); return; } setMessage('Sesión guardada correctamente.'); setShowModal(false); await loadSessions(); await reload(editing?.id); }
  return <div className="stack"><div className="row"><PageTitle title="Sesiones" subtitle="Entrenos, partidos y tryouts." /><button className="icon-btn big" onClick={openCreate}><Plus size={20} /></button></div>{message && <p className={message.includes('correctamente') ? 'success' : 'error'}>{message}</p>}{loadingSessions ? <Card><p>Cargando sesiones...</p></Card> : sessions.map(s => { const isCurrent = selectedSession?.id === s.id; const isMatch = ['friendly_match', 'league_match', 'scrimmage'].includes(s.type); return <Card key={s.id} className={isCurrent ? 'session-card current' : 'session-card'}><button className="list-row-button" onClick={() => { setSelectedSession(s); reload(s.id); }}><div className={isMatch ? 'session-icon match' : 'session-icon training'}>{isMatch ? '⚽' : '🏃'}</div><div><strong>{s.name}</strong><p>{buildSessionLabel(s)}</p><span className="small-muted">{translateSessionType(s.type)} · {s.status}</span></div><button className="chip" onClick={(event) => { event.stopPropagation(); openEdit(s); }}>Editar</button></button></Card>; })}{showModal && <Modal title={editing ? 'Editar sesión' : 'Crear sesión'} onClose={() => setShowModal(false)}><form className="stack" onSubmit={saveSession}><input placeholder="Nombre sesión" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} required /><input type="date" value={form.session_date} onChange={e => setForm({ ...form, session_date: e.target.value })} required /><input type="time" value={form.start_time} onChange={e => setForm({ ...form, start_time: e.target.value })} /><select value={form.type} onChange={e => setForm({ ...form, type: e.target.value })}><option value="training">Entreno</option><option value="friendly_match">Partido amistoso</option><option value="league_match">Partido liga</option><option value="tryout">Tryout</option><option value="scrimmage">Scrimmage</option></select><input placeholder="Responsable" value={form.responsible} onChange={e => setForm({ ...form, responsible: e.target.value })} /><input placeholder="Rival" value={form.opponent} onChange={e => setForm({ ...form, opponent: e.target.value })} /><select value={form.home_away} onChange={e => setForm({ ...form, home_away: e.target.value })}><option value="home">Local</option><option value="away">Visitante</option><option value="neutral">Neutral</option></select><select value={form.status} onChange={e => setForm({ ...form, status: e.target.value })}><option value="planned">Planned</option><option value="completed">Completed</option><option value="archived">Archived</option></select><button className="primary">Guardar sesión</button></form></Modal>}</div>;
}
