import { useEffect, useState } from 'react';
import { supabase } from '../supabase';
import type { Evaluation } from '../types';
import type { AppSession, PlayerCardTotal } from '../utils/appTypes';
import { attendanceOptions, ratingFields } from '../utils/appTypes';
import { formatDate } from '../utils/formatters';
import { getCardWarnings, getRatingCounts } from '../utils/stats';
import { Card, PageTitle } from '../components/ui';

export function SummaryPage() {
  const [mode, setMode] = useState<'session'|'global'>('session'); const [sessions, setSessions] = useState<AppSession[]>([]); const [selectedSessionId, setSelectedSessionId] = useState(''); const [evaluations, setEvaluations] = useState<any[]>([]); const [attendance, setAttendance] = useState<any[]>([]); const [cards, setCards] = useState<any[]>([]); const [globalEvaluations, setGlobalEvaluations] = useState<any[]>([]); const [globalAttendance, setGlobalAttendance] = useState<any[]>([]); const [cardTotals, setCardTotals] = useState<PlayerCardTotal[]>([]);
  async function loadSessions() { const { data } = await supabase.from('sessions').select('*').order('session_date', { ascending: false }); const rows = (data || []) as AppSession[]; setSessions(rows); setSelectedSessionId(rows[0]?.id || ''); }
  async function loadSessionSummary(sessionId: string) { if (!sessionId) return; const ev = await supabase.from('evaluations').select('*, players(display_name)').eq('session_id', sessionId); const att = await supabase.from('attendance').select('*, players(display_name)').eq('session_id', sessionId); const cardRows = await supabase.from('cards').select('*, players(display_name)').eq('session_id', sessionId); setEvaluations(ev.data || []); setAttendance(att.data || []); setCards(cardRows.data || []); }
  async function loadGlobalSummary() { const ev = await supabase.from('evaluations').select('*, players(display_name)'); const att = await supabase.from('attendance').select('*, players(display_name)'); const totals = await supabase.from('player_card_totals').select('*'); setGlobalEvaluations(ev.data || []); setGlobalAttendance(att.data || []); setCardTotals((totals.data || []) as PlayerCardTotal[]); }
  useEffect(() => { loadSessions(); loadGlobalSummary(); }, []); useEffect(() => { if (selectedSessionId) loadSessionSummary(selectedSessionId); }, [selectedSessionId]);
  return <div className="stack"><PageTitle title="Resumen" subtitle="Resumen por sesión y resumen acumulado." /><div className="segmented"><button className={mode === 'session' ? 'selected' : ''} onClick={() => setMode('session')}>Por sesión</button><button className={mode === 'global' ? 'selected' : ''} onClick={() => setMode('global')}>Total</button></div>{mode === 'session' ? <SessionSummary sessions={sessions} selectedSessionId={selectedSessionId} setSelectedSessionId={setSelectedSessionId} evaluations={evaluations} attendance={attendance} cards={cards} /> : <GlobalSummary evaluations={globalEvaluations} attendance={globalAttendance} cardTotals={cardTotals} />}</div>;
}
function SessionSummary({ sessions, selectedSessionId, setSelectedSessionId, evaluations, attendance, cards }: any) { const byScore = [...evaluations].filter((e: Evaluation) => e.total_score).sort((a: any,b: any) => Number(b.total_score)-Number(a.total_score)); const counts = getRatingCounts(evaluations); return <div className="stack"><select value={selectedSessionId} onChange={e => setSelectedSessionId(e.target.value)}>{sessions.map((s: AppSession) => <option key={s.id} value={s.id}>{s.name} · {formatDate(s.session_date)}</option>)}</select><Card className="summary-hero"><div><p className="kicker">Evaluaciones</p><h2>{evaluations.filter((e: any) => e.evaluated).length}</h2></div><div><p className="kicker">Asistencias</p><h2>{attendance.length}</h2></div></Card><Card><p className="kicker">3 jugadores destacados</p>{byScore.slice(0,3).map((e: any,i: number) => <div className="top-row" key={e.id}><span className="rank">#{i+1}</span><strong>{e.players?.display_name}</strong><span>{e.total_score}</span></div>)}</Card><Card><p className="kicker">Tarjetas sesión</p>{cards.length === 0 && <p>Sin tarjetas.</p>}{cards.map((c: any) => <div className="card-alert" key={c.id}><strong>{c.players?.display_name}</strong><span>{c.type}</span></div>)}</Card><Card><p className="kicker">Balance rendimiento equipo</p>{ratingFields.map(([field,label]) => { const high = counts.high[field] || 0; const low = counts.low[field] || 0; const total = Math.max(evaluations.length,1); return <div className="summary-bar" key={field}><div className="summary-top"><strong>{label}</strong><span>{high} altas · {low} bajas</span></div><div className="bar-track"><div className="bar-high" style={{ width: `${(high/total)*100}%` }} /><div className="bar-low" style={{ width: `${(low/total)*100}%` }} /></div></div>; })}</Card></div>; }
function GlobalSummary({ evaluations, attendance, cardTotals }: any) { const cardRows = getCardWarnings(cardTotals); const byPlayer: Record<string, any> = {}; evaluations.forEach((e: any) => { const id = e.player_id; if (!byPlayer[id]) byPlayer[id] = { name: e.players?.display_name || 'Jugador', scores: [], fields: {} }; if (e.total_score) byPlayer[id].scores.push(Number(e.total_score)); ratingFields.forEach(([field]) => { if (!byPlayer[id].fields[field]) byPlayer[id].fields[field] = []; if (e[field]) byPlayer[id].fields[field].push(Number(e[field])); }); }); const bestPlayers = Object.values(byPlayer).map((p: any) => ({ ...p, avg: p.scores.length ? p.scores.reduce((a: number,b: number) => a+b,0)/p.scores.length : 0 })).filter((p: any) => p.avg).sort((a: any,b: any) => b.avg-a.avg); return <div className="stack"><Card><p className="kicker">Tarjetas acumuladas</p>{cardRows.map((c: PlayerCardTotal) => <div className="card-alert" key={c.player_id}><strong>{c.display_name}</strong><span>{c.yellow_cards} 🟨 · {c.red_cards} 🟥</span></div>)}</Card><Card><p className="kicker">Mejores jugadores global</p>{bestPlayers.slice(0,8).map((p: any,i: number) => <div className="top-row" key={p.name}><span className="rank">#{i+1}</span><strong>{p.name}</strong><span>{p.avg.toFixed(1)}</span></div>)}</Card><Card><p className="kicker">Top por disciplina</p>{ratingFields.map(([field,label]) => { const ranking = Object.values(byPlayer).map((p: any) => { const values = p.fields[field] || []; const avg = values.length ? values.reduce((a: number,b: number) => a+b,0)/values.length : 0; return { name: p.name, avg }; }).filter((p: any) => p.avg).sort((a: any,b: any) => b.avg-a.avg)[0]; return <p key={field}><strong>{label}:</strong> {ranking ? `${ranking.name} · ${ranking.avg.toFixed(1)}` : '-'}</p>; })}</Card><Card><p className="kicker">Ranking asistencia</p>{attendanceOptions.filter(([value]) => value !== 'present').map(([value,label]) => { const rows = attendance.filter((a: any) => a.status === value); const grouped: Record<string, number> = {}; rows.forEach((a: any) => { grouped[a.players?.display_name || 'Jugador'] = (grouped[a.players?.display_name || 'Jugador'] || 0) + 1; }); const top = Object.entries(grouped).sort((a,b) => b[1]-a[1])[0]; return <p key={value}><strong>{label}:</strong> {top ? `${top[0]} · ${top[1]}` : '-'}</p>; })}</Card></div>; }
